### ISSUE TITLE
Wallet screening

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/desktop#1074]
Screen destination wallet addresses, for legal reasons

- [x] Create API `GET /valid/:address` -> `200 OK` or `403 Forbidden` https://github.com/filecoin-station/wallet-screening
- [x] Query forbidden addresses
- [ ] Add async validation to destination address input field https://github.com/filecoin-station/desktop/pull/1075

**Comment by bajtos** [comment]
Is it enough to validate the address here in the client? It's relatively easy to bypass this check by either modifying the Station source code or invoking the smart contract directly.

Shouldn't the smart contract reject sanctioned addresses too? (I know this is a much more complex thing to implement.)

**Comment by bajtos** [comment]
How about Station Core? Should it screen the user-provided wallet address, too?

**Comment by juliangruber** [comment]
> Is it enough to validate the address here in the client? It's relatively easy to bypass this check by either modifying the Station source code or invoking the smart contract directly.
> 
> Shouldn't the smart contract reject sanctioned addresses too? (I know this is a much more complex thing to implement.)

We have discussed this in the #station-legal channel (or maybe it was just in the call), client side validation is good enough for now. I also brought up that the only proper way to do this is in the smart contract, unfortunately however Chainalysis' oracle is not published to the Filecoin block chain. Therefore, it would be a significant amount of work (and potentially cost) to mirror it over.

**Comment by juliangruber** [comment]
> How about Station Core? Should it screen the user-provided wallet address, too?

Good idea, let's do that too

https://github.com/filecoin-station/core/issues/249
