### ISSUE TITLE
save logs as dialog opens in background if "save logs" link is clicked when main window not open

### ISSUE THREAD

**Issue by olizilla** [filecoin-station/desktop#1110]
on macos 13.2, if you click "save module logs as" from the system tray icon without the main ui open, the save dialog opens in the background. to the user it looks like clicking the link does nothing. You can find the dialog if you show all open windows and pick it out of the crowd.

**Comment by juliangruber** [comment]
Fixed in https://github.com/filecoin-station/desktop/pull/1116
