### ISSUE TITLE
Payout and Threshold

### ISSUE THREAD

**Issue by BitMaci** [filecoin-station/desktop#1272]
"Scheduled earnings will be sent to your Station Wallet approximately once a month, provided you have earned more than the payout threshold" is the message popping hovering Filecoin Station's scheduled rewards.
So, how much is the threshold, and possibly, when is "once a month"?

**Comment by juliangruber** [comment]
The threshold currently is 0.5 FIL. We have been paying out in the first week of each month recently.

**Comment by BitMaci** [comment]
Thanks
