### ISSUE TITLE
Transfer earnings from previous computer to new computer

### ISSUE THREAD

**Issue by avivash** [filecoin-station/desktop#1289]
I reformatted my Macbook and have my old Filecoin Station saved to a time machine backup on a hard drive. I'm wondering which files I need to copy to my new machine to retain the earnings I made previously? I was nearly at the minimum threshold for being able to transfer, so I'd rather not lose all that time spent. Is this possible?

Thanks

**Comment by bajtos** [comment]
It should be enough to restore `filecoin-station-wallet-0x` item in the `login` keychain. This item holds the seed phrase (mnemonic) for (re)creating your wallet's private keys.

**Comment by avivash** [comment]
That worked! Thank you 🙏🏼

**Comment by juliangruber** [comment]
Please check out https://docs.filstation.app/your-station-wallet#dfd985a50aa346cfbfc7d25d6c84f443
