### ISSUE TITLE
What are the two values right of STATION ADDRESS when you open the wallet?

### ISSUE THREAD

**Issue by ff781** [filecoin-station/desktop#1344]
What are the two values right of STATION ADDRESS when you open the wallet?

the first one starts with

f4

the second one starts with

0x

are these just the filecoin address as well as the EVM compatible address of the wallet you receive your rewards to?

Then do we also get the private key to this wallet or how is it done?

**Comment by juliangruber** [comment]
> are these just the filecoin address as well as the EVM compatible address of the wallet you receive your rewards to?

That's correct!

> Then do we also get the private key to this wallet or how is it done?

Please see https://docs.filstation.app/your-station-wallet#38d1152429cd49eb990ea6d54321ea08 for instructions on how to access your seed phrase.
