### ISSUE TITLE
Show auto-updater status in the top banner when an update is pending

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/desktop#137]
See the Sigma prototype:

<img width="457" alt="Screenshot_2022-09-19_at_15 45 33" src="https://user-images.githubusercontent.com/1140553/191212365-578c59fc-125f-4daa-a31c-7b0f4a32f4b4.png">

See the [Electron docs](https://www.electron.build/auto-update#events) for the full list of events emitted by the auto-updater module. I think we may want to visualise the following:
- `update-available`
- `download-progress`
- `update-downloaded`

**Comment by bajtos** [comment]
The PR #199 added the banner using the current auto-update backend.

I'd like to improve our auto-update implementation to notify the user about all three states (update-available, download-progress, update-downloaded) and offer "restart to upgrade" button only after the new version has been downloaded.

The tray menu items triggered by "Check for updates" should support all three states too.

**Comment by olizilla** [comment]
+1 right now there is no feedback when you click the the "restart now" button in the banner, which is confusing. (i had enough time to get confused, go find liceap, line it up with station and record a screen cap, before the download finished and the dialog popped up at the end of this gif)

![station-no-restart-feedback](https://github.com/filecoin-station/desktop/assets/58871/5ba175b4-ec70-41ad-9439-e292c25673da)
