### ISSUE TITLE
Last week: no rewards / failed to download latest Zinnia module source code

### ISSUE THREAD

**Issue by BitMaci** [filecoin-station/desktop#1399]
![image](https://github.com/filecoin-station/desktop/assets/93403210/df741fb5-dd52-4e43-b24d-b1ae3cfa1931)

Please fix it, it's been 1 week now. Thank you.

**Comment by juliangruber** [comment]
Can you please share module logs? Click on tray icon -> Save Module Logs As...

**Comment by BitMaci** [comment]
![image](https://github.com/filecoin-station/desktop/assets/93403210/86887a29-86f3-4f0b-8dd8-c4f7d093d29e)
![image](https://github.com/filecoin-station/desktop/assets/93403210/6ee909f6-131b-4547-82cf-29e4d127513c)

**Comment by juliangruber** [comment]
Thank you for reporting! I have seen that `lstat` error a couple times, but haven't been able to reproduce it yet. I'm taking another stab at it now.

**Comment by juliangruber** [comment]
Should be fixed in the latest release https://github.com/filecoin-station/core/releases/tag/v20.1.2. Please reopen if it still happens

**Comment by BitMaci** [comment]
![image](https://github.com/filecoin-station/desktop/assets/93403210/ca9a704c-ae4b-4492-a37a-5280b18a15b8)
Thanks for the core update but the issue seems not fixed even after restarting filecoin station. No jobs completed.
