### ISSUE TITLE
Failed to download latest source code on Windows

### ISSUE THREAD

**Issue by BitMaci** [filecoin-station/desktop#1404]
![image](https://github.com/filecoin-station/desktop/assets/93403210/df65d8d5-0014-492e-a6e3-702d9bfd8b25)
After core update issue is not solved.

**Comment by juliangruber** [comment]
Can you please share module logs? Click on tray icon -> Save Module Logs As...

**Comment by BitMaci** [comment]
![image](https://github.com/filecoin-station/desktop/assets/93403210/a2448f33-4389-47e8-a079-0c68b2515e33)

**Comment by juliangruber** [comment]
Is this running inside docker or some other virtualization?

**Comment by BitMaci** [comment]
No, running on windows physical pc ( Win 11 Home)

**Comment by juliangruber** [comment]
Thank you for confirming. I will set up Windows servers running Station now, to help us reproduce.

**Comment by juliangruber** [comment]
This should have been solved
