### ISSUE TITLE
Failed to download latest Zinnia module source code

### ISSUE THREAD

**Issue by GreybeardCrypto** [filecoin-station/desktop#1447]
I just upgraded to 1.4.6 on Windows and after the app starts it says "Updating source code for Zinnia modules...".

After a few minutes it says "Failed to download latest Zinnia module source code"

I checked the log and it repeats this:

> Failed to download voyager source. Retrying...
> [voyager]  ⇣ checking for updates
> [voyager]  ⇣ downloading source files via https://bafkreignngdpq6g7qvai6phpau6jfjk7zvuih7rdf5zdga7jnq7n6zve3a.ipfs.w3s.link?format=car
> [Error: ENOENT: no such file or directory, lstat 'C:\Users\PC\AppData\Local\Temp\Filecoin Station Desktop\sources\voyager'] {
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'lstat',
>   path: 'C:\\Users\\PC\\AppData\\Local\\Temp\\Filecoin Station Desktop\\sources\\voyager',
>   attemptNumber: 6,
>   retriesLeft: 5
> }

I can successfully download the IPFS file in the browser on the same machine so it appears to only be the application having a problem?

**Comment by juliangruber** [comment]
I haven't been able to reproduce this error on my machine yet 🤔

**Comment by GreybeardCrypto** [comment]
Thanks for taking a look. I should have done one as a test but not had any problems in the past. I updated half a dozen machines all at the same time and they all have this issue.

I tried downgrading to 1.3.7 but it now also seems to do this.

Are you able to advise what files/folders I need to remove to reset the install without losing my wallet contents?
