### ISSUE TITLE
after update i receive an error "Failed to Validate FIL_WALLET_ADDRESS address"

### ISSUE THREAD

**Issue by slick202** [filecoin-station/desktop#1521]
I have two station miners running, one is still running fine.

but after i rebooted the computer the other miner cannot Validate FIL_WALLET_ADDRESS

this happens after "loaded station ID" then hangs up and exits the module

not sure if this is a known issue or if there is a fix?

**Comment by BitMaci** [comment]
![image](https://github.com/filecoin-station/desktop/assets/93403210/59650978-3979-4721-b2d6-a1c0f1939c74)

Everything has stopped for me, no logs in app

**Comment by OBitsPlease** [comment]
Im having the exact same issue as BitMaci.. Im guessing this is an API error or something not on my end.   You guys really need a discord to tell the community about updates and bugs

**Comment by BitMaci** [comment]
Working now it fixed itself
