### ISSUE TITLE
Provide data for Desktop v2

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/desktop#1552]
- [x] Modules
- [x] Historic rewards
- [x] https://github.com/filecoin-station/spark-stats/pull/131
- [x] Total received rewards per module
- [x] Total received rewards per participant
- [ ] https://github.com/filecoin-station/desktop/issues/1713

**Comment by patrickwoodhead** [comment]
Historic rewards and total received rewards are covered by the current work scope of Patrick N. Further work is needed to have an API for historic scheduled rewards.
