### ISSUE TITLE
Spark crashed with exit code 1 & Spark exited with code:1 Always ...

### ISSUE THREAD

**Issue by teo4RM4Z** [filecoin-station/desktop#1639]
Spark crashed with exit code 1 & Spark exited with code:1 
![2024-06-23_21-31-14](https://github.com/filecoin-station/desktop/assets/45219117/92d0102c-9e8d-4fe7-9ab9-d91984cf1aa0)
Always ... a few days...

**Comment by bajtos** [comment]
Can you please export module logs (Tray > Save Module Logs As...) and check if there is any relevant information there?

**Comment by bajtos** [comment]
Also, what is your OS (Windows/macOS/Linux) and CPU architecture (Intel or ARM)?

Is there anything specific about the system where the Station runs? (E.g. a different directory where the Station was installed.)

**Comment by teo4RM4Z** [comment]
[station-modules-1719391944484.log](https://github.com/user-attachments/files/15985229/station-modules-1719391944484.log)
Windows 11 pro / Intel i5-9400F / Rx550 8G
Filecoin station 1.6.8 
Nothing special, just a recent problem.

**Comment by teo4RM4Z** [comment]
> 您能否导出模块日志（托盘 > 将模块日志另存为...）并检查其中是否有相关信息？

Thanks

**Comment by nekros05** [comment]
I have the same error, it happened after a reboot.

Windows 10 Pro 22H2 / AMD FX 8350
Filecoin Station v.1.8.6

[station-modules-1719548637641.log](https://github.com/user-attachments/files/16024142/station-modules-1719548637641.log)

**Comment by bajtos** [comment]
Thank you for the details! We have seen this problem in the past, but we were not able to reproduce it ourselves, which makes it difficult for us to fix it 😢 

Let's continue the discussion here: https://github.com/filecoin-station/zinnia/issues/485
