### ISSUE TITLE
Errors when starting v2.0.0 for user testing

### ISSUE THREAD

**Issue by patrickwoodhead** [filecoin-station/desktop#1644]
When I first open v2.0.0, I get the following error screen 

<img width="513" alt="image" src="https://github.com/filecoin-station/desktop/assets/91056047/ffbeea93-68ae-4fc7-94f1-c0b93afcb72d">

Then, when I click OK, the app gets stuck on this page

<img width="1431" alt="image" src="https://github.com/filecoin-station/desktop/assets/91056047/83128540-f415-4841-bbc3-7afcc6587c73">

**Comment by juliangruber** [comment]
Fixed in https://github.com/filecoin-station/desktop/commit/8b7dcf32aa85398c7e6e9d93631ce83548f43b9c, unfortunately I can't publish atm because our code signing certificate expired: https://github.com/filecoin-station/desktop/actions/runs/9740440703/job/26877813217

>   ⨯ Failed to notarize via notarytool.  Failed with unexpected result: 
>
> Error: HTTP status code: 403. A required agreement is missing or has expired. This request requires an in-effect agreement that has not been signed or has expired. Ensure your team has signed the necessary legal agreements and that they are not expired.

**Comment by juliangruber** [comment]
https://github.com/filecoin-station/desktop/releases/tag/v2.0.0-1
