### ISSUE TITLE
It's possible to deselect time range on the main screen

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/desktop#1671]
In the chart on the main screen, it’s possible to deselect time range, i.e. choose neither of 7d/1m/1y/all intervals. The chart does not show any data in such case.

Steps to reproduce: click twice on the same time range button.

<img width="1073" alt="Screenshot 2024-07-04 at 09 03 30" src="https://github.com/filecoin-station/desktop/assets/1140553/f2fc75b3-8164-4d14-8862-14c79a902e1e">

**Comment by juliangruber** [comment]
Fixed in https://github.com/filecoin-station/desktop/pull/1673
