### ISSUE TITLE
prematurely truncated docs on https://docs.filstation.app/spark

### ISSUE THREAD

**Issue by gruns** [filecoin-station/desktop#1764]
here: 

![image](https://github.com/user-attachments/assets/8d431214-dee8-44e6-9a44-0ad8d66daa9d)

i couldnt find a docs repo, or any repo for docs.filestation.app, under https://github.com/filecoin-station to fix and file a PR

**Comment by juliangruber** [comment]
Thank you @gruns, fixed! 🙌 

Docs are living in Notion and deployed via Super

**Comment by gruns** [comment]
closing as complete 🎉 

danke, @juliangruber, du held, du 💪
