### ISSUE TITLE
Unhandled errors in `SimpleURLLoaderWrapper`

### ISSUE THREAD

**Issue by guillempuche** [filecoin-station/desktop#316]
Version: 0.11.2
Mac: Silicon 13.0.1
Using a VPN. I change configurations.

I try to open the app from the menubar and shows this error:

<img width="299" alt="imatge" src="https://user-images.githubusercontent.com/3519924/206125540-86cacbea-c06e-4328-9af7-8a9ee23f2910.png">

I suppose it happened when configuring the VPN. I cannot send you the logs because they're only from the last minutes, not 30 minutes ago.

<img width="845" alt="imatge" src="https://user-images.githubusercontent.com/3519924/206126913-0c188f09-caa8-4c3e-a3d2-21aca4505642.png">

---

Added by @bajtos to make this issue easier to find using text search:

```
Error occured Error: net::ERR_NAME_NOT_RESOLVED at SimpleURLLoaderWrapper. ‹anonymous>
(node:electron/js2c/browser_init: 101:7167) at SimpleURLLoaderWrapper.emit
(node:events:527:28) at SimpleURLLoaderWrapper.emit
(node:domain:475:12)
```

Related issues:
- #222
   > - Likely this is the issue: https://github.com/electron-userland/electron-builder/issues/2398
   > - How to reproduce: https://github.com/electron-userland/electron-builder/issues/2398#issuecomment-376048011
   > - Potential fix: https://github.com/electron-userland/electron-builder/issues/2398#issuecomment-413117520

- #425

**Comment by bajtos** [comment]
Thank you @guillempuche for reporting the issue. I think this could be related to #258.

**Comment by bajtos** [comment]
A slightly different report: https://filecoinproject.slack.com/archives/C03S6LXSRB8/p1673420068248149

```
Error occured
Error: net::ERR_CONNECTION_CLOSED at
SimpleURLLoaderWrapper.<anonymous> (node:electron/is2c/ browser_init:2:49386)
at SimpleURLLoaderWrapper.emit (node:events:513:28)
at SimpleURLLoaderWrapper.emit (node:domain:489:12)
```

<img width="853" alt="image (3)" src="https://user-images.githubusercontent.com/1140553/211855252-0bf14566-1bca-44b3-b9eb-f7895e84dba3.png">

**Comment by guanzo** [comment]
Another error 
![image](https://user-images.githubusercontent.com/4676043/217884862-ad82d441-9bb9-42cd-9bed-fdd75b3cbe98.png)
