### ISSUE TITLE
Support Apple Silicon M1/M2 (darwin arm64)

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/desktop#35]
Improve our build & release setup to produce binaries for `darwin-arm64` platform in addition to `darwin-x86_64`.

Related info:
- https://github.com/electron-userland/electron-builder/pull/5426#issuecomment-749684326
- Example PR adding M1 support to a different project: https://github.com/athensresearch/athens/pull/707

Consider building a universal binary that supports both architectures - see https://github.com/electron/universal

**Comment by bajtos** [comment]
I think we will need to update saturn-l2 release process to notarise the arm64 binary.

See https://github.com/goreleaser/goreleaser/issues/1227 and https://goreleaser.com/customization/sign/?h=gon#with-gon

**Comment by bajtos** [comment]
I opened an issue to fix saturn-l2 darwin-arm64 builds here: https://github.com/filecoin-project/saturn-l2/issues/35

**Comment by juliangruber** [comment]
Won't happen in this sprint, as I'm having apple credential issues, and we don't yet have our own credentials
