### ISSUE TITLE
DRY types

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/desktop#445]
Currently these files have redundant type definitions:

- https://github.com/filecoin-station/filecoin-station/blob/c03028b99272b14c0ad642b98f5583fe63f198b8/main/typings.d.ts
- https://github.com/filecoin-station/filecoin-station/blob/c03028b99272b14c0ad642b98f5583fe63f198b8/renderer/src/typings.d.ts

**Comment by juliangruber** [comment]
@bajtos do you have an idea how to go about this? Shall we make either type file the main one, that the other imports from? Or shall we create a new shared type file?

**Comment by bajtos** [comment]
I would create a new shared type file in a directory that's outside of both the `main` and `renderer` directories. I am concerned that if we access a file in `main` from `renderer` (or vice versa), then it will be difficult to configure TypeScript projects to include only the shared files but ignore the rest.
