### ISSUE TITLE
Rework `ROOT_DIR` to `CACHE_ROOT` and `STATE_ROOT`

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/desktop#606]
Per the discussion in https://github.com/filecoin-station/core/issues/75

Caveat: Saturn L2 node keeps both the state and the cache in a single location configured via `ROOT_DIR`. I think we don't need to fix the node to use two locations, it should be ok to use `CACHE_ROOT` the same way as we are doing now.

**Comment by juliangruber** [comment]
>  I think we don't need to fix the node to use two locations, it should be ok to use CACHE_ROOT the same way as we are doing now.

I'm not sure how big an issue it actually is. If the cache directory gets cleared, the jobs completed count is lost

**Comment by bajtos** [comment]
> If the cache directory gets cleared, the jobs completed count is lost

I know, but since Saturn L2 is a kind of an experimental module running in the testnet, maybe we don't care that much?

Of course, it's better to fix Saturn L2 to keep the job counter file in a different location, but is it worth the effort? Do we have the skill and bandwidth to make those changes?

I am fine either way.
